export const ADD_AUDIENCE = "ADD_AUDIENCE";
export const FETCH_DATA = "FETCH_DATA";
export const DATA_FETCH_ERROR = "DATA_FETCH_ERROR";
export const ADJUST_DISPLAY_RANGE = "ADJUST_DISPLAY_RANGE";
export const TOGGLE_SORT_ORDER = "TOGGLE_SORT_ORDER";
export const TOGGLE_SORT_PARAM = "TOGGLE_SORT_PARAM";
